In [2]:
import numpy as np


In [3]:
a = np.arange(20)
b = np.arange(25)

In [4]:
a
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(type(b))


1
(25,)
25
int64
8
<class 'numpy.ndarray'>


In [7]:
help(a)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [8]:
a = np.array( [1.0, 2.0, 3.0, 4.0, 5.0] )
print(a)
print(a.dtype)
print(type(a))

[1. 2. 3. 4. 5.]
float64
<class 'numpy.ndarray'>


In [9]:
c = np.eye(10)
dtype=np.float64
c

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
d = np.linspace(-1, 2, 15, endpoint=True)
print(d)

[-1.         -0.78571429 -0.57142857 -0.35714286 -0.14285714  0.07142857
  0.28571429  0.5         0.71428571  0.92857143  1.14285714  1.35714286
  1.57142857  1.78571429  2.        ]


In [11]:
d = np.linspace(-1, 2, 15, endpoint=False)
print(d)

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1.   1.2  1.4  1.6
  1.8]


In [12]:
e = np.logspace(-1, 2, 15, endpoint=True, base=10)
print(e)

[  0.1          0.16378937   0.26826958   0.43939706   0.71968567
   1.17876863   1.93069773   3.16227766   5.17947468   8.48342898
  13.89495494  22.75845926  37.2759372   61.05402297 100.        ]


In [13]:
help(np.logspace)

Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, 

In [14]:
fin = np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)
fin

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [15]:
ask = np.arange(12).reshape(3,4)
print(ask)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
ask*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [17]:
a*4

array([ 4.,  8., 12., 16., 20.])

In [19]:
ask + ask

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [21]:
ask*ask

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [23]:
bil = ask.transpose()
bil

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [24]:
ask @ bil

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [25]:
print(ask)
ask.sum(axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

In [26]:
print(ask)
ask.sum(axis=2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


AxisError: ignored

In [27]:
ask.sum()

66

In [28]:
print(ask.min(), ask.max())

0 11


In [29]:
bil = ask*np.pi/12.0
print(bil)

[[0.         0.26179939 0.52359878 0.78539816]
 [1.04719755 1.30899694 1.57079633 1.83259571]
 [2.0943951  2.35619449 2.61799388 2.87979327]]


In [30]:
cat = np.cos(bil)
print(cat)

[[ 1.00000000e+00  9.65925826e-01  8.66025404e-01  7.07106781e-01]
 [ 5.00000000e-01  2.58819045e-01  6.12323400e-17 -2.58819045e-01]
 [-5.00000000e-01 -7.07106781e-01 -8.66025404e-01 -9.65925826e-01]]


In [32]:
die = bil + cat 
print(die)

[[1.         1.22772521 1.38962418 1.49250494]
 [1.54719755 1.56781598 1.57079633 1.57377667]
 [1.5943951  1.64908771 1.75196847 1.91386744]]


In [33]:
ask = np.arange(9)
ask

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
ask[3]

3

In [35]:
ask[4]

4

In [36]:
print(ask[1:3])

[1 2]


In [37]:
ask[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
ask = np.arange(15).reshape(3,5)
ask

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
ask[1,1]

6

In [40]:
ask[0:2,0:2]

array([[0, 1],
       [5, 6]])

In [41]:
ask[:,1]

array([ 1,  6, 11])

In [47]:
ask[:,3]

array([ 3,  8, 13])

In [48]:
ask = ask.flatten()
print(ask)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [50]:
for r in ask:
    print(r)
ask = np.arange(15).reshape(3,5)
print(ask)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [52]:
for e in ask.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [53]:
help(a.flatten())

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [58]:
ask = np.arange(10)
print(ask)

[0 1 2 3 4 5 6 7 8 9]


In [59]:
bil = ask
bil is ask

True

In [60]:
bil.shape = (2, 5)
print(bil)
ask.shape

[[0 1 2 3 4]
 [5 6 7 8 9]]


(2, 5)

In [63]:

bil.shape = (2, 5)
print(bil)
ask.shape

[[0 1 2 3 4]
 [5 6 7 8 9]]


(2, 5)

In [64]:
bil is ask

True

In [65]:
print(ask)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [67]:
ask = np.arange(12)
cat = ask[:]
ask.shape = (3,4)
print(ask)
print(cat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [68]:
cat[1] = -1
print(ask)
print(cat)

[[ 0 -1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0 -1  2  3  4  5  6  7  8  9 10 11]


In [69]:
die = cat[3:8]
print(die)

[3 4 5 6 7]


In [70]:
die[:] = 0 

In [71]:
print(ask)
print(cat)
print(die)

[[ 0 -1  2  0]
 [ 0  0  0  0]
 [ 8  9 10 11]]
[ 0 -1  2  0  0  0  0  0  8  9 10 11]
[0 0 0 0 0]


In [73]:
print(cat is ask)
print(cat.base is ask)
print(cat.flags.owndata)
print(ask.flags.owndata)

False
True
False
True


In [75]:
die = ask.copy()
die[:,:] = 0.0
print(ask)
print(die)

[[ 0 -1  2  0]
 [ 0  0  0  0]
 [ 8  9 10 11]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [76]:
ask = np.arange(12).reshape(3,4)
ask

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
ask[ask > 4] = 0
ask

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [78]:
ask[ask == 0] = -1
ask

array([[-1,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [79]:
ask == -1

array([[ True, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [80]:
ask = np.arange(12).reshape(3,4)
ask[np.logical_and(ask > 3, ask <= 9)] = 0.0
ask

array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [ 0,  0, 10, 11]])

In [81]:
ask > 5

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [83]:
Men = 32
Nem = 64
xmin = ymin = 0.0
xmax = ymax = 1.0

x = np.linspace(xmin, xmax, Men, endpoint=False)
y = np.linspace(ymin, ymax, Nem, endpoint=False)
print(x.shape)
print(y.shape)
y

(32,)
(64,)


array([0.      , 0.015625, 0.03125 , 0.046875, 0.0625  , 0.078125,
       0.09375 , 0.109375, 0.125   , 0.140625, 0.15625 , 0.171875,
       0.1875  , 0.203125, 0.21875 , 0.234375, 0.25    , 0.265625,
       0.28125 , 0.296875, 0.3125  , 0.328125, 0.34375 , 0.359375,
       0.375   , 0.390625, 0.40625 , 0.421875, 0.4375  , 0.453125,
       0.46875 , 0.484375, 0.5     , 0.515625, 0.53125 , 0.546875,
       0.5625  , 0.578125, 0.59375 , 0.609375, 0.625   , 0.640625,
       0.65625 , 0.671875, 0.6875  , 0.703125, 0.71875 , 0.734375,
       0.75    , 0.765625, 0.78125 , 0.796875, 0.8125  , 0.828125,
       0.84375 , 0.859375, 0.875   , 0.890625, 0.90625 , 0.921875,
       0.9375  , 0.953125, 0.96875 , 0.984375])

In [86]:
import time
import numpy as np
Men = 32
Nem = 64

x = np.linspace(0.0, 1.0, Men, endpoint=False)
y = np.linspace(0.0, 1.0, Nem, endpoint=False)

In [87]:
import time
import numpy as np
Men = 32
Nem = 64

x = np.linspace(0.0, 1.0, Men, endpoint=False)
y = np.linspace(0.0, 1.0, Nem, endpoint=True)

In [105]:
t0 = time.time()

g = np.zeros((Men, Nem))

for i in range(Men):
    for j in range(Nem):
        g[i,j] = np.sin(2.0*np.pi*x[i]*y[j])
        
t1 = time.time()

print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.004748344421386719 s


In [106]:
x2d, y2d = np.meshgrid(x, y, indexing="ij")

print(x2d[:,0])
print(x2d[0,:])

print(y2d[:,0])
print(y2d[0,:])

[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0.         0.01587302 0.03174603 0.04761905 0.06349206 0.07936508
 0.0952381  0.11111111 0.12698413 0.14285714 0.15873016 0.17460317
 0.19047619 0.20634921 0.22222222 0.23809524 0.25396825 0.26984127
 0.28571429 0.3015873  0.31746032 0.33333333 0.34920635 0.36507937
 0.38095238 0.3968254  0.41269841 0.42857143 0.44444444 0.46031746
 0.47619048 0.49206349 0.50793651 0.52380952 0.53968254 0.55555556
 0.57142857 0.58730159 0.6031746  0.61904762 0

In [107]:
t0 = time.time()
g2 = np.sin(2.0*np.pi*x2d*y2d)
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.0007641315460205078 s


In [108]:
x = np.array([1, 2, 3, 4])
y = np.array([4, 3, 2, 1])
np.concatenate([y,x])

array([4, 3, 2, 1, 1, 2, 3, 4])

In [110]:
z = [8, 4, 6]
print(np.concatenate([x, y, z]))

[1 2 3 4 4 3 2 1 8 4 6]


In [113]:
grid = np.array([[10, 20, 30],
                 [30, 50, 60]])
np.concatenate([grid, grid])

array([[10, 20, 30],
       [30, 50, 60],
       [10, 20, 30],
       [30, 50, 60]])

In [114]:
np.concatenate([grid, grid], axis=1)

array([[10, 20, 30, 10, 20, 30],
       [30, 50, 60, 30, 50, 60]])

In [115]:
np.concatenate([grid, grid], axis=2)

AxisError: ignored

In [116]:
x = [1, 2, 3, 4, 4, 3 ,2, 1, 9, 4 ,6]
x1, x2, x3,x4 = np.split(x, [3, 5,8])
print(x1, x2, x3, x4)

[1 2 3] [4 4] [3 2 1] [9 4 6]


In [119]:
grid = np.arange(30).reshape((6, 5))
grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [120]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]
 [25 26]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]
 [27 28 29]]


In [124]:
x = np.arange(2, 19)
print(x)
np.add.reduce(x)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


170

In [125]:
np.multiply.reduce(x)

6402373705728000

In [126]:
np.add.accumulate(x)

array([  2,   5,   9,  14,  20,  27,  35,  44,  54,  65,  77,  90, 104,
       119, 135, 152, 170])

In [127]:
np.multiply.accumulate(x)

array([               2,                6,               24,
                    120,              720,             5040,
                  40320,           362880,          3628800,
               39916800,        479001600,       6227020800,
            87178291200,    1307674368000,   20922789888000,
        355687428096000, 6402373705728000])